// // Code generated by MCHP Chatbot

// #include <avr/io.h>
// #include <avr/interrupt.h>
// #include <avr/sleep.h>
// #include <stdio.h>

// #define LED_bm PIN2_bm
// volatile uint8_t shared_flag = 0; // Event flag shared with ISR

// void ADC_init_window(void) 
// {
//     // Reference = 1.024 V
//     VREF.ADC0REF = VREF_REFSEL_1V024_gc;
//     // Average 8 samples, single-ended, 12-bit
//     ADC0.CTRLB = ADC_SAMPNUM_ACC8_gc;
//     ADC0.CTRLC = ADC_PRESC_DIV4_gc;
//     // Input = PD2 (AIN2)
//     ADC0.MUXPOS = ADC_MUXPOS_AIN2_gc;
//     ADC0.CTRLD = ADC_INITDLY_DLY16_gc | ADC_SAMPDLY_DLY2_gc;
//     // Window thresholds
//     ADC0.WINLT = 100; 
//     ADC0.WINHT = 300;
//     // Window comparison mode: fire when outside window
//     ADC0.CTRLE = ADC_WINCM_OUTSIDE_gc;
//     // Enable window comparator interrupt
//     ADC0.INTCTRL = ADC_WCMP_bm;
//     // Enable ADC, run in standby, free-running
//     ADC0.CTRLA = ADC_ENABLE_bm | ADC_FREERUN_bm | ADC_RUNSTBY_bm;
//     ADC0.COMMAND = ADC_STCONV_bm;
// }

// ISR(ADC0_WCMP_vect)
// {
//     uint16_t result = ADC0.RES;
//     ADC0.INTFLAGS = ADC_WCMP_bm; // clear flag
//             if (result < ADC0.WINLT) {
//         PORTA.OUTCLR = LED_bm; // Dark → LED ON (active-low)
//             } else if (result > ADC0.WINHT) {
//         PORTA.OUTSET = LED_bm; // Bright → LED OFF
//             }
//     shared_flag = 1; // Set event flag for main loop to handle
//         }

// void disable_unused_peripherals(void)
// {
//     // Disable unused digital peripherals for lower power
//     USART0.CTRLA = 0;
//     USART0.CTRLB = 0;
//     TCA0.SINGLE.CTRLA = 0;
//     TCB0.CTRLA = 0;
//     ADC0.CTRLA = ADC0.CTRLA; // keep running for window
//     DAC0.CTRLA = 0;

//     SPI0.CTRLA = 0;
//     TWI0.MCTRLA = 0;
//     }

// // Set all unused pins to input, no pull-up, digital input buffer off
// void disable_unused_pins(void)
// {
//     // PA2 is LED output, all others can be input/buffer disabled and NO pull-up
//     PORTA.DIR = LED_bm;           // PA2 out, all else in
//     for (uint8_t i = 0; i < 8; ++i) {
//         if (i != 2) (&PORTA.PIN0CTRL)[i] = PORT_ISC_INPUT_DISABLE_gc; // PAx exclude LED
// }
//     for (uint8_t i = 0; i < 8; ++i) { (&PORTB.PIN0CTRL)[i] = PORT_ISC_INPUT_DISABLE_gc; }
//     for (uint8_t i = 0; i < 8; ++i) { (&PORTC.PIN0CTRL)[i] = PORT_ISC_INPUT_DISABLE_gc; }
//     for (uint8_t i = 0; i < 8; ++i) { (&PORTD.PIN0CTRL)[i] = PORT_ISC_INPUT_DISABLE_gc; }
//     for (uint8_t i = 0; i < 8; ++i) { (&PORTE.PIN0CTRL)[i] = PORT_ISC_INPUT_DISABLE_gc; }
// }

// int main(void)
// {
//     // Set up LED
//     PORTA.DIRSET = LED_bm;
//     PORTA.OUTSET = LED_bm; // LED off (active-low)

//     disable_unused_pins();
//     disable_unused_peripherals();

//     // ADC for event, VREF
//     ADC_init_window();

//     // Disable BOD for lowest power
//     BOD.CTRLA = BOD_SLEEP_DIS_gc | BOD_ACTIVE_DIS_gc;

//     // Main loop power settings
//     set_sleep_mode(SLEEP_MODE_STANDBY);
//     sleep_enable();
//     sei();

//     while (1) {
//         cli();
//         if (shared_flag == 0) {
//             sei();
//             sleep_cpu();
//         }
//         sei();
//         // Handle any shared_flag events (if needed)
//         cli();
//         shared_flag = 0;
//         sei();
//         // Optionally: put any low-power, deferred jobs here
//     }
// }
